/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package netmessage;

import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 *
 * @author cnrobotics
 */
public class Console extends javax.swing.JFrame {
    
    //Constants for NetMessage itself
    public static final SimpleAttributeSet NM_PRE = new SimpleAttributeSet();
    public static final SimpleAttributeSet NM_ERROR = new SimpleAttributeSet();
    public static final SimpleAttributeSet NM_MSG = new SimpleAttributeSet();
            
    private NetMessage nm;
    
    /**
     * Creates new form Console
     */
    public Console() {
        initComponents();
        
        //Add the attributes
        NM_ERROR.addAttribute(StyleConstants.Foreground, Color.RED);
        NM_ERROR.addAttribute(StyleConstants.Bold, true);
        
        NM_MSG.addAttribute(StyleConstants.Foreground, Color.WHITE);
        NM_MSG.addAttribute(StyleConstants.Bold, true);
        
        NM_PRE.addAttribute(StyleConstants.Foreground, Color.BLUE);
        NM_PRE.addAttribute(StyleConstants.Bold, true);
    }
    
    public NetMessage initializeNetMessage() throws IOException {
        nm = new NetMessage();
        return nm;
    }

    public void AppendStyledLine(String text, AttributeSet s){
        try {
            StyledDocument doc = ConsoleTextPane.getStyledDocument();
            doc.insertString(doc.getLength(), text + "\n", s);
            ConsoleTextPane.setStyledDocument(doc);
        } catch (BadLocationException ex) {
            Logger.getLogger(Console.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void AppendStyledText(String text, AttributeSet s){
        try {
            StyledDocument doc = ConsoleTextPane.getStyledDocument();
            doc.insertString(doc.getLength(), text, s);
            ConsoleTextPane.setStyledDocument(doc);
        } catch (BadLocationException ex) {
            Logger.getLogger(Console.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ConsoleTextPane = new javax.swing.JTextPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ConsoleTextPane.setEditable(false);
        ConsoleTextPane.setBackground(new java.awt.Color(0, 0, 0));
        ConsoleTextPane.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(ConsoleTextPane);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        NetMessage connm;
        
        Console con = new Console();
        con.setVisible(true);
        
        con.AppendStyledLine("Welcome to NetMessage!", NM_MSG);
        
        //Try and create a new NetMessage
        try {
            connm = con.initializeNetMessage();
        } catch (IOException ex) {
            ex.printStackTrace();
            con.AppendStyledText("::", NM_PRE);
            con.AppendStyledLine("Could not create a socket on port 123!", NM_ERROR);
        }
        
        con.AppendStyledText("::", NM_PRE);
        con.AppendStyledLine("Successfully created a socket on port 123!", NM_MSG);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane ConsoleTextPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
