/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package netmessage;

import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 *
 * @author cnrobotics
 */
public class Console extends javax.swing.JFrame {
    
    //Constants for NetMessage itself
    public static final SimpleAttributeSet NM_PRE = new SimpleAttributeSet();
    public static final SimpleAttributeSet NM_ERROR = new SimpleAttributeSet();
    public static final SimpleAttributeSet NM_MSG = new SimpleAttributeSet();
            
    private NetMessage nm;
    
    /**
     * Creates new form Console
     */
    public Console() {
        initComponents();
        
        //Add the attributes
        NM_ERROR.addAttribute(StyleConstants.Foreground, Color.RED);
        NM_ERROR.addAttribute(StyleConstants.Bold, true);
        
        NM_MSG.addAttribute(StyleConstants.Foreground, Color.WHITE);
        NM_MSG.addAttribute(StyleConstants.Bold, true);
        
        NM_PRE.addAttribute(StyleConstants.Foreground, Color.BLUE);
        NM_PRE.addAttribute(StyleConstants.Bold, true);
    }
    
    public void initializeNetMessage() throws IOException {
        nm = new NetMessage();
    }
    
    public NetMessage getNetMessage() {
        return this.nm;
    }

    /**
     * Appends the specified text and adds a newline.
     * @param text The text to print to the console
     * @param s An AttributeSet to style the text
     */
    public void AppendStyledLine(String text, AttributeSet s){
        try {
            StyledDocument doc = ConsoleTextPane.getStyledDocument();
            doc.insertString(doc.getLength(), text + "\n", s);
            ConsoleTextPane.setStyledDocument(doc);
        } catch (BadLocationException ex) {
            Logger.getLogger(Console.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * Adds the text to end of the document (Usually on the same line)
     * @param text Text to add
     * @param s An AttributeSet to style the text
     */
    public void AppendStyledText(String text, AttributeSet s){
        try {
            StyledDocument doc = ConsoleTextPane.getStyledDocument();
            doc.insertString(doc.getLength(), text, s);
            ConsoleTextPane.setStyledDocument(doc);
        } catch (BadLocationException ex) {
            Logger.getLogger(Console.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ConsoleTextPane = new javax.swing.JTextPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ConsoleTextPane.setEditable(false);
        ConsoleTextPane.setBackground(new java.awt.Color(0, 0, 0));
        ConsoleTextPane.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(ConsoleTextPane);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Connection");

        jMenuItem2.setForeground(new java.awt.Color(45, 45, 45));
        jMenuItem2.setText("Change Port");
        jMenu3.add(jMenuItem2);

        jMenuItem3.setForeground(new java.awt.Color(45, 45, 45));
        jMenuItem3.setText("Change IP");
        jMenu3.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setForeground(new java.awt.Color(45, 45, 45));
        jMenuItem4.setText("Reconnect");
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane ConsoleTextPane;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
