/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package netmessage;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.ServerSocket;
import java.net.Socket;

/**
 *
 * @author cnrobotics
 */
public class NetMessage {

    //This is the socket we open so the Robot can communitcate with us
    private ServerSocket server;
    //This is the connection generated once the client connects with us
    private Socket client;
    //Anything we get from the Robot will be read by this
    private BufferedReader clientInput;
    //The default port is 5000
    private int port;
    
    /**
     * Creates as new NetMessage object on port 5000.
     * @throws IOException if there is an error creating the socket. Usually it because the port is already bound.
     */
    public NetMessage() throws IOException {
        server = new ServerSocket(5000);
        server.setSoTimeout(10);
        this.port = 5000;
    }
    
    /**
     * Creates a new NetMessages on the specified port.
     * @param port Port number to open NetMessage on
     * @throws IOException if there is an error creating the socket. Usually it's because the port is already bound
     */
    public NetMessage(int port) throws IOException {
        server = new ServerSocket(port);
        server.setSoTimeout(10);
        this.port = port;
    }
    /**
     * Tries to create the connection between the Robot.
     * @throws IOException If a connection could not be established after 10 seconds
     */
    public void createConnection() throws IOException {
        client = server.accept();
        clientInput = new BufferedReader(new InputStreamReader(client.getInputStream()));
    }
    
    /**
     * Reads the latest message from the Robot
     * @return Latest message
     * @throws IOException A line could not be read.
     */
    public String getLine() throws IOException {
        return clientInput.readLine();
    }
    
    /**
     * Gets the Buffered Reader generated by createConnection()
     * @return A BufferedReader
     */
    public BufferedReader getReader() {
        return this.clientInput;
    }
    
    public int getPort() {
        return port;
    }
}
