/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package netmessage.ui;

import java.awt.Color;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/**
 *
 * @author isaac
 */
public class WindowMain extends javax.swing.JFrame {

    //Constants for NetMessage itself
    public static final SimpleAttributeSet NM_PRE = new SimpleAttributeSet();
    public static final SimpleAttributeSet NM_ERROR = new SimpleAttributeSet();
    public static final SimpleAttributeSet NM_MSG = new SimpleAttributeSet();
    public static final SimpleAttributeSet NM_OK = new SimpleAttributeSet();
    
    
    public WindowMain() {
        initComponents();
        
        //Add the attributes
        NM_ERROR.addAttribute(StyleConstants.Foreground, Color.RED);
        NM_ERROR.addAttribute(StyleConstants.Bold, true);
        
        NM_MSG.addAttribute(StyleConstants.Foreground, Color.WHITE);
        NM_MSG.addAttribute(StyleConstants.Bold, true);
        
        NM_PRE.addAttribute(StyleConstants.Foreground, Color.BLUE);
        NM_PRE.addAttribute(StyleConstants.Bold, true);
        
        NM_PRE.addAttribute(StyleConstants.Foreground, Color.GREEN);
        NM_PRE.addAttribute(StyleConstants.Bold, true);
    }

    /**
    * Appends the specified text and adds a newline.
    * @param text The text to print to the console
    * @param s An AttributeSet to style the text
     * @throws javax.swing.text.BadLocationException
    */
    public void AppendStyledLine(String text, AttributeSet s) throws BadLocationException{
        StyledDocument doc = this.ConsoleTextArea.getStyledDocument();
        doc.insertString(doc.getLength(), text + "\n", s);
        this.ConsoleTextArea.setStyledDocument(doc);
    }
    
    /**
    * Adds the text to end of the document (Usually on the same line)
    * @param text Text to add
    * @param s An AttributeSet to style the text
     * @throws javax.swing.text.BadLocationException
    */
    public void AppendStyledText(String text, AttributeSet s) throws BadLocationException{
        StyledDocument doc = this.ConsoleTextArea.getStyledDocument();
        doc.insertString(doc.getLength(), text, s);
        this.ConsoleTextArea.setStyledDocument(doc);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        ConsoleScrollPane = new javax.swing.JScrollPane();
        ConsoleTextArea = new javax.swing.JTextPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NetMessage");

        ConsoleScrollPane.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        ConsoleTextArea.setBackground(java.awt.Color.black);
        ConsoleTextArea.setForeground(java.awt.Color.lightGray);
        ConsoleTextArea.setText("Welcome to NetConsole!");
        ConsoleScrollPane.setViewportView(ConsoleTextArea);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Connection");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ConsoleScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ConsoleScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ConsoleScrollPane;
    private javax.swing.JTextPane ConsoleTextArea;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
